receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"
  prometheus:
    endpoint: "0.0.0.0:9464"
  azuremonitor:  
    # endpoint is the uri used to communicate with Azure Monitor(append /v2/track to the uri)
    endpoint: ""
    # instrumentation_key is the unique identifer for your Application Insights resource
    instrumentation_key: ""
    # maxbatchsize is the maximum number of items that can be queued before calling to the configured endpoint
    maxbatchsize: 100
    # maxbatchinterval is the maximum time to wait before calling the configured endpoint.
    maxbatchinterval: 10s

processors:
  batch:  

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [zipkin,azuremonitor]
      processors: [batch]
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
      processors: [batch]