global:
  scrape_interval: 15s # Default is every 1 minute.

scrape_configs:
  - job_name: 'otlp'
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ['otlp:4317']